version: "3.8"
services:
  init_faceworker:
    container_name: init_faceworker
    image: alloranetwork/allora-chain:latest
    volumes:
      - ./data:/data
    entrypoint: /data/scripts/init.sh


  inference:
    container_name: inference-hf
    build:
      context: .
      dockerfile: Dockerfile_inference
    command: python -u /app/app.py
    ports:
      - "8000:8000"


  faceworker:
    container_name: faceworker
    build:
     context: .
     dockerfile: Dockerfile
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        if [ ! -f /data/keys/priv.bin ]; then
          echo "Generating new private keys..."
          mkdir -p /data/keys
          cd /data/keys
          allora-keys
        fi
        allora-node \
        --role=worker \
        --peer-db=/data/worker/peer-database \
        --function-db=/data/worker/function-database \
        --runtime-path=/app/runtime \
        --runtime-cli=bls-runtime \
        --private-key=/data/keys/priv.bin \
        --workspace=/data/worker/workspace \
        --log-level=debug \
        --port=9010 \
        --boot-nodes=/dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk,/dns/head-5-p2p.testnet-1.testnet.allora.network/tcp/32135/p2p/12D3KooWAazxKoYszYt4XhCrGWoEUyAFMaU7DB9RZ8TsA7qwLfin,/dns/head-4-p2p.testnet-1.testnet.allora.network/tcp/32134/p2p/12D3KooWRF8HNU21AukE7KC6kZqxqvCiZ5nM9xcLW4YvsuGAYbcm,/dns/head-3-p2p.testnet-1.testnet.allora.network/tcp/32133/p2p/12D3KooWDrArwBSCNxwL3mgJ2NaUygdtPtiwVQtPJafyAH6FSiUf \
        --topic=allora-topic-%topic-id%-worker \
        --allora-node-rpc-address=https://allora-rpc.testnet-1.testnet.allora.network \
        --allora-chain-home-dir=/data/.allorad \
        --allora-chain-key-name=faceworker \
        --allora-chain-topic-id=%topic-id%
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file:
      - .env
    ports:
      - "9010:9010"
    depends_on:
      - init_faceworker
